# -*- coding: utf-8 -*-
"""Hotel Project Group 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIrKN3832RUGjdRYcPbFk60xpYlHlLuy
"""

print("welcome")
print ("Choose The city from the below list you want to book a Room" )
print ("Cities in which rooms are available:")
hotel_locations = ["Goa","Jaipur","Chennai","Bangalore","Delhi","Lucknow","Ludhiana"]
for i in hotel_locations:
    print(i)
for indexes,locations in enumerate(hotel_locations):
    print ("To choose",locations,"Type",indexes+1)
choose_your_destination=int(input())
for i in range(len(hotel_locations)):
  if(choose_your_destination==i):
      print("hotels available in",hotel_locations[i-1])
print("Room Types Available")
roomtypes=["Single Non-Ac","Single Ac","Deluxe Double ","Family room"]
for index,typesofroom in enumerate(roomtypes):
    print("Type",index+1,"for",typesofroom)
wroomwant=int(input("What type of room you want?  ~  "))
wroomwant
costperday=[1500,2200,3400,4800]
for i in range(1,5):
    if wroomwant==i:
      print("Cost Per Night Of a  ",roomtypes[i-1],"room is ","~~",costperday[i-1])
tnGuests=int(input("How many persons are you?      " ))
print("         ")
print("         ")
print("Total Number of Guests","~"," ",tnGuests)
def inputhere():
    input()
def func1(tnGuests):
    for i in range(1,tnGuests+1):
        print("Enter ","person " ,i," Name", " below ","  and then press  ~Enter~")
        inputhere()
func1(tnGuests)
randlist1=[]
mnumber=int(input("Enter Your Mobile Number  "))
strmnumber=str(mnumber)
for i in strmnumber:
    randlist1.append(i)
randlist1
if len(randlist1)==10:
    print("THANKS")
    print("Mobile Number  ~  ",mnumber,end='')
else:
    print("Enter Your Number Correctly")
checkinda=int(input("Enter ~ Check In Date  ~   "))
checkinmo=input("Enter ~ Check In Month In Lower Case ~   ")
checkinye=int(input("Enter ~ Check In Year ~  "))
Months=["January","February","March","April","May","June","July","August","September","October","November","December"]
months=[]
for i in Months:
    months.append(i.casefold())
print (months)
checkouda=int(input("Enter ~ Check Out Date  ~   "))
checkoumo=input("Enter ~ Check Out Month In Lower Case~   ")
checkouye=checkinye
if months.index(checkoumo)>=months.index(checkinmo) and checkinmo==checkoumo and checkinye==checkouye:
    totalnights=checkouda-checkinda
    print(totalnights)
elif months.index(checkoumo)>=months.index(checkinmo) and (checkinye==checkouye) and checkinmo==Months[0] or Months[2] or Months[4] or Months[6] or Months[7] or Months[9] or Months[11]or months[0] or months[2] or months[4] or months[6] or months[7] or months[9] or months[11]:
    totalnights=31-checkinda+checkouda+(months.index(checkoumo)-months.index(checkinmo)-1)*30
    print(totalnights)
elif months.index(checkoumo)>=months.index(checkinmo) and (checkinye==checkouye) and checkinmo==Months[3] or Months[5] or Months[8] or Months[10]  or months[3] or months[5] or months[8] or months[10]  :
    totalnights==30-checkinda+checkouda+(months.index(checkoumo)-months.index(checkinmo)-1)*30
    print(totalnights)
elif months.index(checkoumo)>=months.index(checkinmo) and (checkinye==checkouye) and checkinmo==Months[1] or months[1] and checkinye%2==0 :
    totalnights==29-checkinda+checkouda+(months.index(checkoumo)-months.index(checkinmo)-1)*30
    print(totalnights)
elif months.index(checkoumo)>=months.index(checkinmo) and (checkinye==checkouye) and checkinmo==Months[1] or months[1] and checkinye%2 :
    totalnights==28-checkinda+checkouda+(months.index(checkoumo)-months.index(checkinmo)-1)*30
    print(totalnights)
elif (checkoutye-checkinye>=2):
    print("Invalid Details Provided")
    print("Either you have entered invalid details or your accomodation",end=' ')
    print("period exceeds our limit.")
    print("Sorry For Inconvenience")
else:
    print("confused oonga boonga")
yototabill=totalnights*costperday[wroomwant-1]
if totalnights>=1 and totalnights<=30:
    yototabill=totalnights*costperday[wroomwant-1]
    print("Your Total Bill is Rs",yototabill,"only","inclusive of all taxes and without discounts.")
else:
    print("We think you have entered wrong details or your accomodation period exceeds our limits.")
    print("In Either Case Sorry For Inconvenience")
if  yototabill<=9999 and yototabill>=100:
    print("Total Amount to be paid after discounts and offers  ~  ",0.95*yototabill)
elif yototabill>=10000 and yototabill<=20000:
    print("Total Amount to be paid after discount and offers  ~  ",0.85*yototabill)
elif yototabill>=20001 and yototabill<=30000:
    print("Total Amount to be paid  after discount and offers ~  ",0.75*yototabill)
elif yototabill>=30001:
    print("Total Amount to be paid after discount and offers  ~  ",0.70*yototabill)
else:
    print("Our System Is Detecting Some Errors,Please Enter The Details Again.")
 print("ANMOL")
